"""empty message

Revision ID: b83bdf0b392c
Revises: d27b5bb19be6
Create Date: 2024-05-14 14:28:11.498362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83bdf0b392c'
down_revision = 'd27b5bb19be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.alter_column('production_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.alter_column('production_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
